### ISSUE TITLE
Please add the 7272 reflector for PAPA system

### ISSUE THREAD

**Issue by Desertmansd** [g4klx/P25Clients#121]
Can you please add TG 7272  216.240.173.55  41000

This is a reflector that is tied to the PAPA analog system 

Thank you

73
W6SAT

**Comment by mrickey** [comment]
For this repository, do the developers prefer a request in this form or would they prefer a pull request?

I haven't participated in this repository before, so I'm asking before helping...

Michael AF6FB

**Comment by g4klx** [comment]
A pull request is preferred because it means less work for us! 😀


Sent from Yahoo Mail for iPhone


On Thursday, July 30, 2020, 17:50, Michael Rickey <notifications@github.com> wrote:




For this repository, do the developers prefer a request in this form or would they prefer a pull request?

I haven't participated in this repository before, so I'm asking before helping...

Michael AF6FB

**Comment by g4klx** [comment]
I've added it anyway. All done.
