### ISSUE TITLE
Pi-Star Host

### ISSUE THREAD

**Issue by kc5jmj** [g4klx/P25Clients#158]
how can we go about getting our P25 TG added to Pi-Star Host

**Comment by g4klx** [comment]
Ideally you’d do a pull request, but failing that, giving the details here will suffice.


Sent from Yahoo Mail for iPhone


On Tuesday, December 15, 2020, 02:35, kc5jmj <notifications@github.com> wrote:




how can we go about getting our P25 TG added to Pi-Star Host

**Comment by kc5jmj** [comment]
sorry i could not find any information on how to submit or where that's why I posted here for the request

31337       bridge.kc5jmj.com        41000

**Comment by kc5jmj** [comment]
i tryed doing it but not sure how to do the pull request

**Comment by g4klx** [comment]
I can add the information, can you tell me what the TG is for, and where it’s bridged to, if at all.
Jonathan G4KLX 


Sent from Yahoo Mail for iPhone


On Tuesday, December 15, 2020, 12:31, kc5jmj <notifications@github.com> wrote:




sorry i could not find any information on how to submit or where that's why I posted here for the request

31337 bridge.kc5jmj.com 41000

**Comment by kc5jmj** [comment]
its for SWLA and its bridged to our DMR TG 311995 and Dstar XLX337

**Comment by g4klx** [comment]
Added
