### ISSUE TITLE
P25Hosts.txt Update

### ISSUE THREAD

**Issue by JaredSmudde** [g4klx/P25Clients#477]
Hello,

I was needing a new P25 reflector added to P25Hosts.txt

31217 Central Illinois Skywarn - Linked to Brandmeister TG 311899

31217    tg31217.kd9koo.com    41000

Thank you and 73,
Jared
KD9KOO

**Comment by g4klx** [comment]
Done

**Comment by JaredSmudde** [comment]
Much appreciated!! Just curious, how long does it usually take to propagate into Pi-Star? I ran an update on one of my Pi-Star installs and didn’t see it yet.

**Comment by g4klx** [comment]
I recommend WPSD over Pi-Star these days since it is much more up-to-date. Both Pi-Star and WPSD update overnight, so you should see it tomorrow I suppose.


Sent from Yahoo Mail for iPhone


On Friday, January 12, 2024, 16:10, Jared Smudde ***@***.***> wrote:




Much appreciated!! Just curious, how long does it usually take to propagate into Pi-Star? I ran an update on one of my Pi-Star installs and didn’t see it yet.
